### ISSUE TITLE
Audo update

### ISSUE THREAD

**Issue by noescapin** [lsellens/script.module.audo-programs#1]
Hey there,

running newest openelec on my pi2 and since today a msg pops up that audo detected an update.. it stopps the service, trying to restart and then back from beginning, loop starts

Reboot changed nothing

**Comment by aschnabl** [comment]
I've got the same issue, so I've added a log file:
http://xbmclogs.com/pjupwcul1

**Comment by lsellens** [comment]
Pushing a fix for this to the repo now
