### ISSUE TITLE
Manual Post Processing failed - UnicodeEncodeError

### ISSUE THREAD

**Issue by aschnabl** [lsellens/script.module.audo-programs#7]
After the most recent update to sickrage I get the following error when manually post processing a number of files. Not all fail, maybe half.

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 124: ordinal not in range(128)

The most recent failure was on file: 

[sickrage.log.txt](https://github.com/lsellens/script.module.audo-programs/files/34357/sickrage.log.txt)
Processing /storage/videos/Downloads/New TV Shows/How.to.Get.Away.With.Murder.S01E13.720p.WEB-DL.DD5.1.H.264-BS.NL-sub.mkv (None)"

**Comment by lsellens** [comment]
That's a sickrage error it's not specific to audo. Please report it to sickrage.
https://github.com/SiCKRAGETV/sickrage-issues
