### ISSUE TITLE
Sickrage fails to start after Kodi restart

### ISSUE THREAD

**Issue by Serg86** [lsellens/script.module.audo-programs#8]
Hi, I've had this problem for a long time now on OpenELEC and now on LibreELEC (Raspberry Pi 2).

I use Moonlight (Nvidia Gamestream) to stream games from my PC to my TV. In order for Moonlight to work, Kodi needs to be stopped first, which also stops AUDO. When you exit Moonlight, Kodi restarts itself no problem, AUDO starts up, Sabnzbd and Couchpotato start fine (I don't use Headphones), but SickRage doesn't. No log entry, it just crashes after trying to start. I have to reboot the Pi to get Sickrage back.

I vaguely remember on the OpenELEC forum, you said AUDO needs to start within Kodi namespace, or something to that effect. How can I start Sickrage from command line via SSH?

Ideally, I would love to just start Sab, Sickrage and Couchpotato independently of Kodi, so they keep running even if Kodi doesn't. Simply knowing the command to restart Sickrage the way AUDO would, would also solve my problem though.

Thank you.

**Comment by ramonskie** [comment]
```
python /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/SickBeard.py --pidfile=/var/run/sickbeard.pid --datadir /storage/.kodi/userdata/addon_data/script.service.audo --config=/storage/.kodi/userdata/addon_data/script.service.audo/sickbeard.ini --daemon

```

**Comment by Serg86** [comment]
Thank you, after executing the command I think I finally figured out why it didn't work. The pidfile was still present and it failed to start because of it. I added a simple rm command to the moonlight startup script and it seems to work now.

**Comment by Serg86** [comment]
Could you perhaps help me with SABnzbd? I tried to start it with the command I got with the ps command, but it says the python module Cheetah is required. Sickrage and Couchpotato start fine.

**Comment by ramonskie** [comment]
see https://github.com/lsellens/script.service.audo/issues/20

**Comment by lsellens** [comment]
Please install this and let me know if your issue still exists.
http://lsellens.openelec.tv/addons/devrepo/script.service.audo/script.service.audo-1.3.0~beta1.zip

**Comment by lsellens** [comment]
Since no response I'm going to close this. Reopen if the problem still exists on the current version
